# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tweet',
        ),
    ]
