# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_perfil_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_tweet'),
        ),
    ]
