# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180801_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retweet',
            name='tweet',
        ),
        migrations.AddField(
            model_name='retweet',
            name='tweet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Tweet'),
            preserve_default=False,
        ),
    ]
