# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180801_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='contenido',
            field=models.CharField(max_length=140, verbose_name=''),
        ),
    ]
