# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180801_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respuesta',
            new_name='Comentario',
        ),
        migrations.RenameModel(
            old_name='Amigo',
            new_name='Seguir',
        ),
        migrations.RemoveField(
            model_name='seguidor',
            name='seguidores',
        ),
        migrations.RemoveField(
            model_name='seguidor',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='seguir',
            old_name='siguiendo',
            new_name='seguidos',
        ),
        migrations.DeleteModel(
            name='Seguidor',
        ),
    ]
