# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180801_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='favorito',
            field=models.ManyToManyField(blank=True, to='home.Perfil'),
        ),
    ]
