# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tweet_favorito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='favorito',
            new_name='like',
        ),
    ]
