# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180802_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retweet',
            name='usuario',
        ),
        migrations.AddField(
            model_name='retweet',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Perfil'),
            preserve_default=False,
        ),
    ]
