# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180802_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='comentario',
            field=models.ManyToManyField(blank=True, to='home.Comentario'),
        ),
    ]
