# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180803_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='comentario',
            field=models.ManyToManyField(blank=True, null=True, to='home.Comentario'),
        ),
    ]
