# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180803_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='comentario',
        ),
    ]
