# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_tweet_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comentario',
            field=models.ManyToManyField(blank=True, to='home.Comentario'),
        ),
    ]
