# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_tweet_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfiles', models.ManyToManyField(to='home.Perfil')),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='like',
        ),
        migrations.AddField(
            model_name='tweet',
            name='es_retweet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='tweet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Tweet'),
        ),
    ]
