# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20180805_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='perfiles',
            new_name='likes',
        ),
    ]
