# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180805_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='tweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='like',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Like'),
            preserve_default=False,
        ),
    ]
