# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20180805_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Like'),
        ),
    ]
