# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20180805_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sitioweb',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
