# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20180806_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='enviado',
        ),
    ]
