# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20180806_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat2',
            name='ultimo_mensaje',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
