# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20180807_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='tweet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Tweet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(max_length=140, verbose_name=''),
        ),
    ]
