# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20180808_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='fecha_like',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
