# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_like_fecha_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguir',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
