# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20180809_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguir',
            name='seguidos',
        ),
        migrations.RemoveField(
            model_name='seguir',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Seguir',
        ),
    ]
