# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_seguir'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seguir',
            new_name='Siguiendo',
        ),
    ]
