# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-09 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20180809_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=140, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(verbose_name=''),
        ),
    ]
